arch: s390x
services:
    - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOTTOKEN && cd s390x/Dockerfile && docker build . --tag quay.io/ibmz/alpine:3.12 && docker push quay.io/ibmz/alpine:3.12
